from __future__ import annotations

# Maps Russian label patterns (regex) to VehiclePassportData field names
FIELD_MAPPING: dict[str, str] = {
    r"номер\s+эптс": "epts_number",
    r"идентификационный\s+номер\s+\(vin\)": "vin",
    r"номер\s+птс": "pts_number",
    r"марка": "brand",
    r"коммерческое\s+наименование": "model",
    r"наименование\s+\(тип\)\s+тс": "vehicle_type",
    r"категория\s+тс": "category",
    r"год\s+изготовления": "year",
    r"цвет": "color",
    r"номер\s+кузова": "body_number",
    r"номер\s+шасси": "chassis_number",
    r"страна\s+изготовления": "country_of_manufacture",
    r"номер\s+двигателя": "engine_number",
    r"тип\s+двигателя": "engine_type",
    r"мощность\s+двигателя": "engine_power_kw",
    r"рабочий\s+объём\s+двигателя": "engine_volume",
    r"тип\s+топлива": "fuel_type",
    r"экологический\s+класс": "eco_class",
    r"разрешённая\s+максимальная\s+масса": "max_mass",
    r"масса\s+без\s+нагрузки": "curb_mass",
    r"количество\s+мест": "seats_count",
    r"наименование\s+изготовителя": "manufacturer_name",
    r"инн\s+изготовителя": "manufacturer_inn",
    r"страна\s+нахождения\s+изготовителя": "manufacturer_country",
    r"номер\s+одобрения\s+типа": "otts_number",
    r"дата\s+одобрения\s+типа": "otts_date",
    r"таможенная\s+декларация": "customs_declaration",
    r"наименование\s+владельца": "owner_name",
    r"инн\s+владельца": "owner_inn",
    r"огрн\s+владельца": "owner_ogrn",
    r"адрес\s+владельца": "owner_address",
    r"дата\s+выдачи": "issue_date",
    r"кем\s+выдан": "issuer",
}

# Maps English field names to Russian display labels
RU_LABELS: dict[str, str] = {
    "epts_number": "Номер ЭПТС",
    "vin": "Идентификационный номер (VIN)",
    "pts_number": "Номер ПТС",
    "brand": "Марка",
    "model": "Коммерческое наименование",
    "vehicle_type": "Наименование (тип) ТС",
    "category": "Категория ТС",
    "year": "Год изготовления",
    "color": "Цвет",
    "body_number": "Номер кузова",
    "chassis_number": "Номер шасси",
    "country_of_manufacture": "Страна изготовления",
    "engine_number": "Номер двигателя",
    "engine_type": "Тип двигателя",
    "engine_power_kw": "Мощность двигателя (кВт)",
    "engine_power_hp": "Мощность двигателя (л.с.)",
    "engine_volume": "Рабочий объём двигателя",
    "fuel_type": "Тип топлива",
    "eco_class": "Экологический класс",
    "max_mass": "Разрешённая максимальная масса",
    "curb_mass": "Масса без нагрузки",
    "seats_count": "Количество мест",
    "manufacturer_name": "Наименование изготовителя",
    "manufacturer_inn": "ИНН изготовителя",
    "manufacturer_country": "Страна нахождения изготовителя",
    "otts_number": "Номер одобрения типа",
    "otts_date": "Дата одобрения типа",
    "customs_declaration": "Таможенная декларация",
    "owner_name": "Наименование владельца",
    "owner_inn": "ИНН владельца",
    "owner_ogrn": "ОГРН владельца",
    "owner_address": "Адрес владельца",
    "issue_date": "Дата выдачи",
    "issuer": "Кем выдан",
}
